import "./globals.css"
import BottomTabBar from "@/components/BottomTabBar"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import ClientLayout from "@/components/ClientLayout"
import InstallPWA from "@/components/InstallPwa"

export const metadata = {
  title: "Safar Sathi - Premium Car Rentals & Taxi Services in Dewas, Indore, Ujjain | 24/7 Cab Booking",
  description: "Safar Sathi offers premium taxi services, car rentals, and cab bookings in Dewas, Indore, Ujjain, and surrounding areas. Book 24/7 reliable taxi services for local rides, airport transfers, outstation trips, temple tours, and corporate travel. Affordable AC/Non-AC cabs with verified drivers, instant booking, and safe rides for families, tourists, and business travelers across Madhya Pradesh.",
 
  keywords: [
    // Your existing keywords
    "Taxi service in Dewas",
    "Dewas taxi service",
    "Cab booking Dewas",
    "Taxi booking Dewas",
    "Best taxi in Dewas",
    "Cheapest taxi Dewas",
    "Affordable taxi service Dewas",
    "Dewas cab service",
    "Local taxi in Dewas",
    "Car rental in Dewas",
    "Car hire Dewas",
    "One-way taxi Dewas",
    "Round-trip cab Dewas",
    "24/7 taxi service Dewas",
    "Online cab booking Dewas",
    "Dewas ride booking",
    "Fast taxi Dewas",
    "Safe taxi Dewas",
    "Taxi near Dewas bus stand",
    "Taxi near Dewas railway station",
    "Dewas car rental service",
    "Verified drivers Dewas",
    "Low price cab Dewas",
    "AC taxi Dewas",
    "Non-AC taxi Dewas",
    "Taxi near A.B. Road Dewas",
    "Taxi near MG Road Dewas",
    "Dewas city taxi",
    "Dewas premium cab",
    "Best cab operator Dewas",
    "Taxi near Teen Batti Square",
    "Taxi near Itawa Square",
    "Taxi near Industrial Area Dewas",
    "Taxi near Radhaganj Dewas",
    "Cab from Dewas to nearby cities",
    "Corporate taxi Dewas",
    "Dewas cab for families",
    "Taxi near Chamunda Mata Road",
    "Taxi near Siyaganj Dewas",
    "Taxi near Uday Nagar Dewas",
    "Auto rickshaw Dewas",
    "Auto booking Dewas",
    "E-rickshaw Dewas",
    "Local auto Dewas",
    "Auto near Dewas railway station",
    "Auto near Dewas bus stand",
    "Budget auto Dewas",
    "Auto hire Dewas",
    "E-rickshaw booking Dewas",
    "Auto stand in Dewas",
    "Cheap auto ride Dewas",
    "Short ride auto Dewas",
    "Auto near Itawa",
    "Auto near A.B. Road Dewas",
    "E-rickshaw near Teen Batti",
    "Auto for Dewas to Indore",
    "Quick auto booking Dewas",
    "Auto near Bhopal Square",
    "24/7 auto Dewas",
    "Auto fare Dewas",
    "E-rickshaw fare Dewas",
    "Auto for factories Dewas",
    "Pickup auto Dewas",
    "Dewas industrial area auto",
    "Auto for city ride Dewas",
    "Auto ride app Dewas",
    "Meter auto Dewas",
    "Auto rickshaw service Dewas",
    "Reliable auto Dewas",
    "E-rickshaw for Dewas local ride",
    "Taxi near Dewas Industrial Area",
    "Taxi near Tata Motors Dewas",
    "Taxi near Sunpharma Dewas",
    "Taxi near Vardhman Mills Dewas",
    "Taxi near Abhilasha Colony",
    "Taxi near Meera Hills Dewas",
    "Taxi near Kalani Bag Dewas",
    "Taxi near Dilip Nagar",
    "Taxi near Amba Hills Dewas",
    "Taxi near Gomti Nagar Dewas",
    "Taxi near Ujjain Road Dewas",
    "Taxi near Maksi Road Dewas",
    "Taxi near Bank Note Press (BNP)",
    "Taxi near Dream City",
    "Taxi near Siyaganj Dewas",
    "Taxi near MG Road Dewas",
    "Taxi near Bhopal Road Dewas",
    "Taxi near Rasulpur Dewas",
    "Taxi near Rajendra Nagar Dewas",
    "Taxi near Kalani Nagar Dewas",
    "Taxi near ABC Circle Dewas",
    "Taxi near Ganga Nagar",
    "Taxi near A.B. Road bypass",
    "Taxi near Teen Batti Dewas",
    "Taxi near Kshipra River Dewas",
    "Taxi near Uday Nagar Dewas",
    "Taxi near Radhaganj",
    "Taxi near Gulmohar Colony",
    "Taxi near Patel Nagar",
    "Taxi near Housing Board Colony",
    "Taxi near Dewas Stadium",
    "Taxi near Keladevi Mandir Road",
    "Taxi near Government Hospital Dewas",
    "Taxi near Shanti Nagar Dewas",
    "Taxi near Asha Colony",
    "Taxi near Dewas Court",
    "Taxi near Dewas City Centre",
    "Taxi near Industrial Pump House",
    "Taxi near Nipaniya Road",
    "Taxi near Dewas Sports Club",
    "Dewas to Indore taxi",
    "Dewas to Ujjain taxi",
    "Dewas to Bhopal taxi",
    "Dewas to Maksi taxi",
    "Dewas to Sonkatch taxi",
    "Dewas to Hatpipliya taxi",
    "Dewas to Shajapur taxi",
    "Dewas to Agar taxi",
    "Dewas to Badnawar taxi",
    "Dewas to Ratlam taxi",
    "Dewas to MHOW taxi",
    "Dewas to Pithampur taxi",
    "Dewas to Omkareshwar taxi",
    "Dewas to Mandu taxi",
    "Dewas to Maheshwar taxi",
    "Dewas to Harda taxi",
    "Dewas to Khandwa taxi",
    "Dewas to Burhanpur taxi",
    "Dewas to Dhar taxi",
    "Dewas to Khargone taxi",
    "Dewas to Sendhwa taxi",
    "Dewas to Udaipur taxi",
    "Dewas to Kota taxi",
    "Dewas to Jaipur taxi",
    "Dewas to Ahmedabad taxi",
    "Dewas to Surat taxi",
    "Dewas to Vadodara cab",
    "Dewas to Nashik taxi",
    "Dewas to Pune cab",
    "Dewas to Mumbai taxi",
    "Dewas to Sanchi taxi",
    "Dewas to Pachmarhi taxi",
    "Dewas to Jabalpur taxi",
    "Dewas to Gwalior taxi",
    "Dewas to Neemuch taxi",
    "Dewas to Mandsaur taxi",
    "Dewas to Barwaha taxi",
    "Dewas to Indore airport taxi",
    "Dewas outstation taxi",
    "One-way taxi Dewas",
    "Dewas multi-city cab",
    "Dewas long-distance taxi",
    "Dewas outstation car rental",
    "Best outstation taxi Dewas",
    "Affordable outstation cab Dewas",
    "Dewas highway taxi",
    "SUV taxi Dewas for long trip",
    "Sedan taxi Dewas",
    "Dewas to Mahakal Mandir taxi",
    "Dewas to Indore station taxi",
    "Dewas to Indore airport taxi",
    "Indore airport pickup Dewas",
    "Indore airport drop from Dewas",
    "Airport taxi Dewas",
    "Cheapest airport taxi Dewas",
    "Dewas airport cab booking",
    "Dewas early morning airport taxi",
    "Dewas late night airport taxi",
    "Airport ride Dewas",
    "Dewas airport transfer",
    "Indore airport Dewas cab",
    "Best airport taxi Dewas",
    "SUV airport taxi Dewas",
    "Sedan airport taxi Dewas",
    "Family airport taxi Dewas",
    "Verified airport cab Dewas",
    "Indore airport to Dewas drop",
    "Pre-book airport taxi Dewas",
    "Fast airport ride Dewas",
    "Dewas airport road taxi",
    "Airport pickup Dewas city",
    "Dewas to RAU via airport taxi",
    "Safe taxi for airport Dewas",
    "Cab for early flight Dewas",
    "Airport cab near A.B. Road Dewas",
    "Airport pickup from Industrial Area",
    "Corporate airport taxi Dewas",
    "24/7 airport cab Dewas",
    "Dewas airport travel service",
    "Airport taxi number Dewas",
    "Kaila Devi temple taxi Dewas",
    "Dewas Mata Mandir taxi",
    "Chamunda Mata Mandir taxi",
    "Dewas sightseeing taxi",
    "Dewas tourism cab",
    "Dewas 1-day city tour",
    "Dewas heritage tour taxi",
    "Dewas spiritual tour cab",
    "Taxi for Kaila Mata Darshan",
    "Dewas tourist places taxi",
    "Dewas local sightseeing cab",
    "Dewas city tour packages",
    "Taxi for Tekri Mata Mandir",
    "Devi Mata hill taxi Dewas",
    "Dewas temple taxi",
    "Tourism car rental Dewas",
    "Taxi for picnic spots Dewas",
    "Dewas park taxi rides",
    "Taxi for shopping Dewas",
    "Dewas Mandi taxi",
    "Dewas bus stand pickup",
    "Taxi for religious trips Dewas",
    "Landmark taxi Dewas",
    "Taxi for Balaji Temple Dewas",
    "Taxi for rural Dewas travel",
    "Taxi for city market Dewas",
    "Hilltop Mata Mandir taxi",
    "Dewas temple circuit taxi",
    "Dewas tourist ride service",
    "Taxi near Dewas stadium",
    "Dewas taxi fare",
    "Cab fare Dewas",
    "Taxi rate Dewas",
    "Auto fare Dewas",
    "Dewas cab per km rate",
    "Dewas taxi fare list",
    "Cheapest taxi fare Dewas",
    "Dewas to Indore fare",
    "Dewas to Ujjain fare",
    "Dewas airport taxi fare",
    "Dewas one-way fare",
    "Taxi charges Dewas",
    "Dewas ride start price",
    "Car rental price Dewas",
    "Outstation fare Dewas",
    "Local ride fare Dewas",
    "Affordable taxi rate Dewas",
    "Dewas cab cost",
    "Low price taxi Dewas",
    "Fare calculator Dewas taxi",
    "Best taxi for Dewas city",
    "Cheap taxi for Dewas local ride",
    "Dewas city tour cab price",
    "Safe taxi for women Dewas",
    "Reliable cab service Dewas",
    "Dewas ride for industrial visits",
    "Taxi for factory visit Dewas",
    "Taxi for Dewas industries",
    "Taxi for workers transport Dewas",
    "Cab for Dewas factory shift",
    "Dewas company cab service",
    "Dewas student discount taxi",
    "Taxi for Dewas coaching areas",
    "Dewas senior citizen taxi",
    "Cab for Dewas market ride",
    "Taxi for Dewas late night",
    "Early morning taxi Dewas",
    "Cab for Dewas weddings",
    "Dewas event cab",
    "Dewas office pickup taxi",
    "Dewas corporate travel",
    "Dewas car hire with driver",
    "SUV rental Dewas",
    "Cheapest Outstation cab Dewas",
    "Best taxi operator in Dewas",
    "Dewas trustworthy cab",
    "Taxi for emergency Dewas",
    "Cab for hospital visit Dewas",
    "Dewas doorstep cab",
    "Dewas quick ride booking",
    "Dewas trip taxi",
    "Dewas highway pickup taxi",
    "Cab for long ride Dewas",
    "Dewas weekend taxi",
    "Best taxi for family Dewas",
    "Dewas business travel taxi",
    "Taxi from Dewas hotels",
    "Dewas 2-hour cab service",
    "Taxi for Dewas night market",
    "Cab to Dewas city center",
    "Safar Sathi Dewas",
    "Safar Sathi taxi Dewas",
    "Safar Sathi cab booking Dewas",
    "Safar Sathi car rental Dewas",
    "Safar Sathi ride Dewas",
    "Safar Sathi auto Dewas",
    "Safar Sathi outstation Dewas",
    "Safar Sathi Dewas app",
    "Safar Sathi drivers Dewas",
    "Safar Sathi contact Dewas",
    "Safar Sathi local ride Dewas",
    "Safar Sathi airport cab Dewas",
    "Safar Sathi Dewas city service",
    "Safar Sathi Dewas booking",
    "Safar Sathi 24/7 Dewas taxi",
    "Safar Sathi Dewas website",
    "Safar Sathi pickup Dewas",
    "Safar Sathi drop Dewas",
    "Safar Sathi near me Dewas",
    "Safar Sathi Dewas route taxi",
    "Dewas Kumbh Mela taxi",
    "Dewas festival taxi",
    "Dewas corporate pickup",
    "Dewas intercity travel",
    "Taxi availability Dewas",
    "Dewas tourism rides",
    "Dewas tour operator",
    "Dewas travel booking",
    "Dewas ride-hailing service",
    "Dewas private cab operator",
    "Taxi service in Indore",
    "Indore taxi service",
    "Cab booking Indore",
    "Taxi booking Indore",
    "Best taxi service in Indore",
    "Cheapest taxi Indore",
    "Affordable cab in Indore",
    "Indore cab service",
    "Local taxi Indore",
    "Car rental in Indore",
    "Car hire Indore",
    "One-way cab Indore",
    "Round-trip taxi Indore",
    "Online cab booking Indore",
    "24/7 taxi service Indore",
    "Instant cab Indore",
    "Safe taxi Indore",
    "Indore ride booking",
    "Indore city taxi",
    "Taxi near Indore railway station",
    "Taxi near Indore bus stand",
    "Indore car rental service",
    "Verified drivers Indore",
    "Indore premium cab",
    "Indore auto + cab service",
    "Low price taxi in Indore",
    "Top taxi company Indore",
    "Cab for families Indore",
    "AC taxi Indore",
    "Non-AC cab Indore",
    "Taxi near Vijay Nagar Indore",
    "Taxi near Palasia Indore",
    "Taxi near Rajwada Indore",
    "Taxi near Bhawarkua Indore",
    "Taxi near Khajrana Temple",
    "Best cab operator Indore",
    "Indore travel cab",
    "Corporate cab Indore",
    "Taxi in Indore city center",
    "Taxi near Sarafa Indore",

    "Auto booking Indore",
    "E-rickshaw Indore",
    "Auto near Vijay Nagar",
    "Auto near Rajendra Nagar",
    "Budget auto Indore",
    "E-rickshaw near Rajwada",
    "Indore auto ride",
    "Auto for local travel Indore",
    "E-rickshaw service Indore",
    "Indore auto rental",
    "Cheap auto Indore",
    "Auto hire in Indore",
    "Auto near Indore railway station",
    "Auto near bus stand",
    "24/7 auto Indore",
    "Auto ride Palasia",
    "Auto ride Bhawarkua",
    "Auto for Khandwa Road",
    "E-rickshaw for Indore city",
    "Auto for Sarafa nightlife",
    "Auto near Khajrana Mandir",
    "Indore book auto online",
    "Short distance auto Indore",
    "Auto fare Indore",
    "E-rickshaw fare Indore",
    "Reliable auto in Indore",
    "Meter auto Indore",
    "Quick auto Indore",
    "Indore local ride auto",
    "Auto stand near Rajwada",

    "Indore airport taxi",
    "Taxi from Indore airport",
    "Indore airport cab",
    "Devi Ahilya Bai Airport taxi",
    "Airport pickup Indore",
    "Airport drop taxi Indore",
    "Indore airport to city cab",
    "Airport taxi Vijay Nagar",
    "Airport taxi Palasia",
    "Airport ride for early morning",
    "Cheapest airport taxi Indore",
    "Airport to Ujjain taxi",
    "Airport to Dewas taxi",
    "Airport to Pithampur taxi",
    "Airport transfer Indore",
    "Airport car rental Indore",
    "Airport cab for business travel",
    "Indore airport prepaid taxi",
    "Taxi outside Indore airport",
    "Airport to MHOW taxi",
    "Airport to Rau taxi",
    "Airport to Rajwada taxi",
    "Airport pickup late night",
    "Verified airport taxi Indore",
    "Safe airport drop Indore",
    "Airport cab service for families",
    "Airport to Omkareshwar taxi",
    "Airport to Mandu taxi",
    "Airport taxi Indore online booking",
    "Book ride from Indore airport",
    "Luxury airport taxi Indore",
    "SUV airport taxi Indore",
    "Sedan airport taxi Indore",
    "Cheapest airport pickup Indore",
    "Indore airport outstation cab",
    "Airport long distance taxi",
    "Indore airport travel service",
    "Cab from airport to hotel Indore",
    "Airport pickup by Safar Sathi",
    "Airport group taxi Indore",

    "Indore to Ujjain taxi",
    "Indore to Dewas cab",
    "Indore to Bhopal taxi",
    "Indore to Omkareshwar taxi",
    "Indore to Mandu cab",
    "Indore to Maheshwar taxi",
    "Indore to Sanchi cab",
    "Indore to Ratlam taxi",
    "Indore to Dhar taxi",
    "Indore to MHOW cab",
    "Indore to Pithampur taxi",
    "Indore to Khargone cab",
    "Indore to Barwani taxi",
    "Indore to Sendhwa taxi",
    "Indore to Pune cab",
    "Indore to Mumbai taxi",
    "Indore to Nashik cab",
    "Indore to Ahmedabad taxi",
    "Indore to Surat taxi",
    "Indore to Vadodara cab",
    "Indore to Jaipur taxi",
    "Indore to Kota cab",
    "Indore to Gwalior taxi",
    "Indore to Jabalpur taxi",
    "Indore to Rewa cab",
    "Indore to Nagda taxi",
    "Indore to Neemuch cab",
    "Indore to Shajapur taxi",
    "Indore to Harda cab",
    "Indore to Khandwa taxi",
    "Indore to Burhanpur cab",
    "Indore to Itarsi taxi",
    "Indore to Betul cab",
    "Indore to Amravati taxi",
    "Indore to Dhule cab",
    "Indore to Jalgaon taxi",
    "Indore to Indore airport taxi",
    "Indore intercity cab service",
    "Indore long-distance taxi",
    "Indore outstation cab service",
    "Best outstation taxi Indore",
    "Affordable outstation cab Indore",
    "One-way cab from Indore",
    "Indore outstation car rental",
    "SUV outstation cab Indore",
    "Sedan outstation cab Indore",
    "Indore 24/7 outstation taxi",
    "Indore multi-city cab",
    "Travel from Indore by cab",
    "Indore tourist outstation cab",

    "Taxi near Vijay Nagar",
    "Taxi near Palasia",
    "Taxi near Rajwada",
    "Taxi near Bhawarkua",
    "Taxi near LIG Square",
    "Taxi near Bengali Square",
    "Taxi near Khajrana Mandir",
    "Taxi near Treasure Island Mall",
    "Taxi near C21 Mall",
    "Taxi near Choithram",
    "Taxi near MR10",
    "Taxi near Rau",
    "Taxi near MHOW",
    "Taxi near Pithampur",
    "Taxi near Rajendra Nagar",
    "Taxi near Annapurna Temple",
    "Taxi near Geeta Bhawan",
    "Taxi near MIG Colony",
    "Taxi near Airport Road",
    "Taxi near Ring Road",
    "Taxi near Kanadia Road",
    "Taxi near Bypass Road",
    "Taxi near Pipliya Rao",
    "Taxi near Saket Nagar",
    "Taxi near Airport Square",
    "Taxi near Navlakha",
    "Taxi near Indrapuri",
    "Taxi near Lokmanya Nagar",
    "Taxi near Silicon City",
    "Taxi near Lasudia Mori",
    "Taxi near Nanda Nagar",
    "Taxi near Kalani Nagar",
    "Taxi near Patnipura",
    "Taxi near Robot Square",
    "Taxi near Malwa Mill",
    "Taxi near Radisson Indore",
    "Taxi near Hotel Sayaji",
    "Taxi near Phoenix Citadel",
    "Taxi near Best Price",
    "Taxi near Bombay Hospital",

    "Khajrana Mandir taxi",
    "Khajrana Temple cab booking",
    "Indore sightseeing taxi",
    "Indore city tour cab",
    "Indore Darshan taxi",
    "Indore tourism cab",
    "Lal Bagh Palace taxi",
    "Rajwada Palace taxi",
    "Indore night tour cab",
    "Sarafa night street taxi",
    "Temple tour Indore",
    "Annapurna Mandir taxi",
    "Bijasan Mandir taxi",
    "ISKCON Indore cab",
    "Indore tourist places taxi",
    "Zoo taxi Indore",
    "Safari park taxi Indore",
    "Pipliyapala Regional Park taxi",
    "Indore 1-day tour cab",
    "Indore tourist package taxi",
    "Indore heritage tour cab",
    "Indore spiritual tour taxi",
    "Indore temple circuit cab",
    "Best tourist cab Indore",
    "Indore travel guide taxi",
    "Tourist cab operator Indore",
    "Safe tourist taxi Indore",
    "Indore sightseeing car rental",
    "Day trip Indore cab",
    "Tourist ride Indore",

    "Indore taxi fare",
    "Indore cab fare",
    "Per km rate taxi Indore",
    "Cab charges Indore",
    "Taxi rate Indore",
    "Auto fare Indore",
    "Indore airport taxi fare",
    "Indore to Ujjain fare",
    "Cheapest taxi fare Indore",
    "Low price cab Indore",
    "Indore taxi fare list",
    "Car rental price Indore",
    "Budget cab Indore",
    "Taxi cost in Indore",
    "Outstation taxi fare Indore",
    "Local ride fare Indore",
    "One-way cab fare Indore",
    "Fare calculator taxi Indore",
    "Indore cab starting price",
    "Affordable taxi rate Indore",

    "Best taxi for Indore airport",
    "Indore city tour cab price",
    "Which taxi is cheapest in Indore",
    "Safe cab at night in Indore",
    "Indore corporate travel taxi",
    "Indore office pickup cab",
    "Family cab for Indore sightseeing",
    "Best car rental for Indore",
    "Indore student discount cab",
    "Indore senior citizen taxi",
    "Taxi for late night Indore",
    "Taxi for early morning flight Indore",
    "Cab for AB Road Indore",
    "Cab for Ring Road Indore",
    "Indore travel agency cab booking",
    "Best taxi operator in Indore",
    "Indore quick ride booking",
    "Reliable cab in Indore",
    "Cab for hospital visit Indore",
    "Indore doorstep cab",
    "Cheapest airport drop Indore",
    "Best taxi for family Indore",
    "Indore car hire with driver",
    "SUV rental Indore",
    "Self-drive car rental Indore",
    "Cab for business meeting Indore",
    "Indore-to-city hotel drop taxi",
    "Indore safe women taxi",
    "Cab from Indore hotels",
    "Indore 2-hour cab service",
    "Cab for Sarafa night market",
    "Indore point-to-point taxi",
    "Taxi for marriage event Indore",
    "Indore long trip cab",
    "Indore weekend taxi",
    "Indore taxi for tourists",
    "Reliable airport transfer Indore",
    "Indore VIP cab service",
    "Indore ride for shopping",
    "Cab to Meghdoot Garden Indore",

    "Safar Sathi Indore",
    "Safar Sathi taxi Indore",
    "Safar Sathi cab booking Indore",
    "Safar Sathi airport taxi Indore",
    "Safar Sathi car rental Indore",
    "Safar Sathi ride booking Indore",
    "Safar Sathi Indore travel",
    "Safar Sathi Vijay Nagar cab",
    "Safar Sathi Palasia cab",
    "Safar Sathi Rajwada taxi",
    "Safar Sathi Indore app",
    "Safar Sathi drivers Indore",
    "Safar Sathi local ride Indore",
    "Safar Sathi corporate cab Indore",
    "Safar Sathi outstation Indore",
    "Safar Sathi airport pickup",
    "Safar Sathi contact Indore",
    "Safar Sathi rental cab Indore",
    "Safar Sathi nearby taxi",
    "Safar Sathi premium cab Indore",

    // Additional 10 SEO-boosting keywords
    "Madhya Pradesh taxi service",
    "Central India car rental",
    "MP tourism cab service",
    "Religious tour taxi Madhya Pradesh",
    "Business travel cab MP",
    "Affordable intercity taxi service",
    "Premium car hire Madhya Pradesh",
    "24/7 cab service near me",
    "Online taxi booking app",
    "Trusted cab service MP"
  ],
  openGraph: {
    title: "Safar Sathi - Premium Taxi Services in Dewas, Indore & Ujjain",
    description: "Book reliable 24/7 taxi services, car rentals, and cab bookings across Dewas, Indore, Ujjain. Airport transfers, outstation trips, temple tours with verified drivers.",
    url: "https://safar--sathi.vercel.app/",
    siteName: "Safar Sathi",
    images: [
      {
        url: "/icons/icon-512x512.png",
        width: 1200,
        height: 630,
        alt: "Safar Sathi - Premium Taxi Services",
      },
    ],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Safar Sathi - Premium Taxi Services in MP",
    description: "24/7 reliable taxi services in Dewas, Indore, Ujjain. Book cabs for local rides, airport transfers, outstation trips & temple tours.",
    images: ["/icons/icon-512x512.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: "https://safar--sathi.vercel.app/",
  },
  manifest: "/manifest.json",
  themeColor: "#3b82f6",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Safar Sathi - Taxi Services",
  },
  formatDetection: {
    telephone: true,
    date: true,
    address: true,
    email: true,
  },
  category: "travel",
  classification: "taxi service, car rental, transportation, hotel booking",
  authors: [{ name: "Safar Sathi Team" }],
  publisher: "Safar Sathi",
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ PWA Essentials */}
        <meta name="application-name" content="Safar Sathi" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Safar Sathi" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="theme-color" content="#f97316" />
        <meta name="background-color" content="#ffffff" />
        <meta name="google-site-verification" content="zqC-69tz8B1VhINUghxq96W2BgClagcAIvgQKh7Lqi4" />
        <link rel="manifest" href="/manifest.json" crossOrigin="use-credentials" />

        {/* ✅ App Icons for Android/iOS */}
        <link rel="apple-touch-icon"  type="image/png" sizes="any" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="/favicon.svg" />
        <link rel="icon" type="image/png" sizes="any" href="/favicon.ico" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </head>

      <body className="antialiased">
        <ClientLayout>
          <Header />
          {children}
          <InstallPWA />
          <Footer />
        <BottomTabBar />
        </ClientLayout>
      </body>
    </html>
  )
}
